name: 3. Publish

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Publish to GHCR
        uses: e621ng/publish-to-ghcr@v1
